name:         aoc2020
version:      0.1.0.0
github:       "epilanthanomai/aoc2020-hs"
license:      GPL-3.0-or-later
author:       "Hope Ranker"
maintainer:   "hope.ranker@gmail.com"
copyright:    "Copyright: (c) 2020 Hope Ranker"
description:  "Advent of Code 2020 implementation"

extra-source-files:
- README.md

source-dirs:  .
data-files:
- samples/*.txt
- input/*.txt

dependencies:
- base >= 4.7 && < 5

executables:
  day01:
    main:           day01.hs
  day02:
    main:           day02.hs
  day03:
    main:           day03.hs
  day04:
    main:           day04.hs
  day05:
    main:           day05.hs
  day06:
    main:           day06.hs
    dependencies:   unordered-containers
  day07:
    main:           day07.hs
  day08:
    main:           day08.hs
    dependencies:
    - transformers
    - vector
